version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: coreai3d_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pmAkRV4lAAKsOfdWCUxP
      MYSQL_DATABASE: CoreAI3D
    ports:
      - "33060:33060" # X Plugin
      - "3306:3306"   # classic protocol
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password

  coreai3d:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coreai3d
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 33060
      DB_USER: root
      DB_PASSWORD: pmAkRV4lAAKsOfdWCUxP
      DB_SCHEMA: CoreAI3D
    ports:
      - "8080:8080" # Assuming your app listens on 8080
    volumes:
    #Change to release
      - ./out/build/linux-x64-debug-wsl/CoreAI3D/CoreAI3D:/app/CoreAI3D

volumes:
  mysql_data: