if(EXISTS "D:/code/CoreAI3D/tests/CoreAI3D_GTest[1]_tests.cmake")
  include("D:/code/CoreAI3D/tests/CoreAI3D_GTest[1]_tests.cmake")
else()
  add_test(CoreAI3D_GTest_NOT_BUILT CoreAI3D_GTest_NOT_BUILT)
endif()
